spring.application.name=Loan Management System


# MongoDB configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=loandb
spring.data.mongodb.auto-index-creation=false

# Multipart file upload configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Server configuration
server.port=8080

# JWT configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# Application-specific properties
app.file.upload-dir=./uploads

# Default admin bootstrap (for local/dev)
#app.bootstrap.admin.enabled=true
#app.bootstrap.admin.username=admin
#app.bootstrap.admin.email=admin@lms.com
#app.bootstrap.admin.password=Admin@123

# Stripe (set STRIPE_SECRET_KEY in environment)
stripe.secret-key=sk_test_51T0IZ0CCxgCxcgAYz0AnnREYTSDCX7rHWxgGvO8b9F2Q48rVfR72ZF8Bny7UCwQed3cDll6GXJTJ5Qsl6b9THCUg00zux5kgdt
stripe.publishable-key=pk_test_51T0IZ0CCxgCxcgAYe2IzrczC0puSrU2zVbQOfzfaN6mCKgziHmrJKYUwK0vLrBKauJHUzNd2CAx79JzSaArDaZmO00ZjS5UAB8
stripe.currency=INR
